service: private-tutor

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    timeout: 120  # Timeout in seconds
    events:
      - http:
          path: /
          method: get
      - http:
          path: /teachers
          method: get
      - http:
          path: /teachers/{id}
          method: get
      - http:
          path: /teachers
          method: post
      - http:
          path: /teachers/{id}
          method: put
      - http:
          path: /teachers/{id}
          method: delete
      - http:
          path: /api-docs
          method: get
      - http:
          path: /batches/teacher/{teacherId}
          method: get
      - http:
          path: /batches/{id}
          method: get
      - http:
          path: /batches
          method: post
      - http:
          path: /batches/{id}
          method: put
      - http:
          path: /batches/{batchId}/student/{studentId}
          method: patch
      - http:
          path: /batches/{id}
          method: delete
      - http:
          path: /students
          method: get
      - http:
          path: /students/{id}
          method: get
      - http:
          path: /students/batch/{batchId}
          method: get
      - http:
          path: /students
          method: post
      - http:
          path: /students/{id}
          method: put
      - http:
          path: /students/{id}
          method: delete
      - http:
          path: /messages/batch/{batchId}
          method: get
      - http:
          path: /messages/student/{studentId}
          method: get
      - http:
          path: /messages/{id}
          method: get
      - http:
          path: /messages
          method: post
      - http:
          path: /messages/{id}/reply
          method: patch
      - http:
          path: /messages/{id}
          method: delete
      - http:
          path: /fee-records/batch/{batchId}/student/{studentId}
          method: get
      - http:
          path: /fee-records/{id}
          method: get
      - http:
          path: /fee-records
          method: post
      - http:
          path: /fee-records/{id}
          method: patch
      - http:
          path: /fee-records/{id}
          method: delete
      - http:
          path: /assignments/batch/{batchId}
          method: get
      - http:
          path: /assignments/batch/{batchId}/student/{studentId}
          method: get
      - http:
          path: /assignments/{id}
          method: get
      - http:
          path: /assignments
          method: post
      - http:
          path: /assignments/{id}
          method: put
      - http:
          path: /assignments/{id}
          method: delete
      - http:
          path: /login/teacher
          method: post
      - http:
          path: /login/student
          method: post
      - http:
          path: /uploads
          method: post
      - http:
          path: /notifications/teachers/{teacherId}
          method: get
      - http:
          path: /notifications/{notificationId}/seen
          method: patch
      - http:
          path: /notifications/students/{studentId}
          method: get
      - http:
           path: /notes
           method: post
      -  http:
           path: /notes/batch/{batchId}
           method: get
      - http:
           path: /notes/student/{id}
           method: get
      - http:
           path: /notes/{id}
           method: put 
      - http:
           path: /notes/{id}
           method: delete          
      - http:
           path: /tests
           method: post
      - http:
           path: /tests/batches/{batchId}
           method: get
      - http:        
           path: /tests/{id}
           method: get
      - http:    
           path: /tests/{id}
           method: put
      - http:           
           path: /tests/{id}
           method: delete
      - http:
          path: /test-results
          method: post
      - http:
          path: /test-results/{id}
          method: put
      - http:
          path: /test-results/{id}
          method: get
      - http:
          path: /test-results/tests/{testId}
          method: get
      - http:
          path: /test-results/students/{studentId}
          method: get
      - http:
          path: /test-results/{id}
          method: delete