service: private-tutor

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /teachers
          method: get
      - http:
          path: /teachers/{id}
          method: get
      - http:
          path: /teachers
          method: post
      - http:
          path: /teachers/{id}
          method: put
      - http:
          path: /teachers/{id}
          method: delete
      - http:
          path: /api-docs
          method: get
      - http:
          path: /batches/teacher/{teacherId}
          method: get
      - http:
          path: /batches/{id}
          method: get
      - http:
          path: /batches
          method: post
      - http:
          path: /batches/{id}
          method: put
      - http:
          path: /batches/{id}
          method: delete
      - http:
          path: /students
          method: get
      - http:
          path: /students/{id}
          method: get
      - http:
          path: /students
          method: post
      - http:
          path: /students/{id}
          method: put
      - http:
          path: /students/{id}
          method: delete
      - http:
          path: /messages/batch/{batchId}
          method: get
      - http:
          path: /messages/batch/{batchId}/student/{studentId}
          method: get
      - http:
          path: /messages/{id}
          method: get
      - http:
          path: /messages
          method: post
      - http:
          path: /messages/{id}/reply
          method: patch
      - http:
          path: /messages/{id}
          method: delete
      - http:
          path: /fee-records/batch/{batchId}/student/{studentId}
          method: get
      - http:
          path: /fee-records/{id}
          method: get
      - http:
          path: /fee-records
          method: post
      - http:
          path: /fee-records/{id}
          method: patch
      - http:
          path: /fee-records/{id}
          method: delete




