service: private-tutor

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /teachers
          method: get
      - http:
          path: /teachers/{id}
          method: get
      - http:
          path: /teachers
          method: post
      - http:
          path: /teachers/{id}
          method: put
      - http:
          path: /teachers/{id}
          method: delete
      - http:
          path: /api-docs
          method: get
      - http:
          path: /batches/teacher/{teacherId}
          method: get
      - http:
          path: /batches/{id}
          method: get
      - http:
          path: /batches
          method: post
      - http:
          path: /batches/{id}
          method: put
      - http:
          path: /batches/{id}
          method: delete




